// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPEr9e108W5VXUFYOrJDJm3HFhmx4b44',
    appId: '1:39697647783:web:47b57312f5b08d26bb3382',
    messagingSenderId: '39697647783',
    projectId: 'movies-cfc57',
    authDomain: 'movies-cfc57.firebaseapp.com',
    storageBucket: 'movies-cfc57.appspot.com',
    measurementId: 'G-V77FSDXFCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTGB57evGvA633yDjRPvWJbqRYXggTIGQ',
    appId: '1:39697647783:android:561c6a5c411cafbcbb3382',
    messagingSenderId: '39697647783',
    projectId: 'movies-cfc57',
    storageBucket: 'movies-cfc57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKr4Z1mECRkldIMMhzzDD6aBAA5C__sd8',
    appId: '1:39697647783:ios:74b0c9a8d31fa2b1bb3382',
    messagingSenderId: '39697647783',
    projectId: 'movies-cfc57',
    storageBucket: 'movies-cfc57.appspot.com',
    iosClientId: '39697647783-lphd701prmbgbq95kabetif8k5ri7c36.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTv',
  );

  static const webClientId =
      '39697647783-sg98roqblt4bmg026ahmo1d0egfujque.apps.googleusercontent.com';
}
